# Finally Clause:-
# The finally code block is also a part of exception handling.When we handle exception using the try and except block, we can include a finally block at the end and it is always executed.

# Syntax:-
# try:
#     statements which could generate Exception
# except:
#     solution of genereated Exception
# finally:
#     block of code which is going to execute in any situation

try:
    l = [1, 5, 6, 7]
    i = int(input("Enter index: "))
    print(l[i])
except Exception as e:
    print(e)
finally:
    print("I am always executed")
